name: enigma
description: Command-line interface (CLI) for generating a Flutter project
version: 1.0.15
repository: #TODO

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  dio: ^5.4.0
  get_it: ^7.6.7
  logger: ^2.0.2+1
  args: ^2.4.2
  dcli: ^3.3.2
  mason_logger: ^0.2.6
  archive: ^3.4.10

  json_ast: ^1.0.6
  convert: ^3.0.1
  dart_style: ^2.2.1
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1

executables:
  enigma:

