name: dev_pilot
description: Command-line interface (CLI) for generating a Flutter project
version: 1.0.13
repository: #TODO

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.19.5 <4.0.0'



dependencies:
  dio: ^5.4.0
  get_it: ^7.6.7
  logger: ^2.0.2+1
  args: ^2.4.2
  dcli: ^3.3.2
  mason_logger: ^0.2.6
  archive: ^3.4.10

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1

executables:
  dev_pilot:

